### ISSUE TITLE
Moving the robot

### ISSUE THREAD

**Issue by bsverdin** [bsverdin/The-loaughgndthoe-files#1]
We need code to have it detect the direction of the joystick, the direction of loaughgndthoe, and apply the direction of the joystick to it.

**Comment by bsverdin** [comment]
also, the button needs to tell the arm to move (which i still don't know how the arm moves)

**Comment by davidmuchow** [comment]
how did you come up with loaughgndthoe

**Comment by bsverdin** [comment]
it's pronounced Ronda, but basically we took confusing English word
pronunciations and used them to create the name Ronda.
